server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600

      discovery:
        locator:
          enabled: false

      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**

        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-}%X{spanId:-}] %logger{36} - %msg%n"