server:
  port: 8761
spring:
  application:
    name: discovery-server
  profiles:
    active: local
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-}%X{spanId:-}] %logger{36} - %msg%n"
