server:
  port: 8094
spring:
  application:
    name: cart-service
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://ep-morning-water-atadw7qz.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_usCBTgn9do2t
cart:
  kafka:
    rest:
      url: https://kafka-16753a04-rajureddy-3ab4.k.aivencloud.com:19417
      username: avnadmin
      password: AVNS_fZ62eT6MQ64mWuqeVVd
      topic: cart-events
  sql:
    init:
      mode: always
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-}%X{spanId:-}] %logger{36} - %msg%n"
